</div>
<footer class="sticky-footer bg-white">
  <div class="container my-auto">
    <div class="copyright text-center my-auto">
      <span>Copyright &copy; APOTEK MAHABBAH 2023</span>
    </div>
    <!-- <div>Logo generated by <a href="https://www.designevo.com/" title="Free Online Logo Maker">DesignEvo free logo designer</a></div> -->
  </div>
</footer>
</div>

<div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
  aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Logout dari aplikasi?</h5>
        <button class="close" type="button" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">x</span>
        </button>
      </div>
      <div class="modal-body">
        Pilih "Logout" untuk melanjutkan keluar dari aplikasi.
      </div>
      <div class="modal-footer">
        <button class="btn btn-secondary" type="button" data-dismiss="modal">
          Cancel
        </button>
        <a class="btn btn-info" href="logout.php">Logout</a>
      </div>
    </div>
  </div>
</div>
        <!-- Scroll to Top Button-->
        <a class="scroll-to-top rounded" href="#page-top">
      <i class="fas fa-angle-up"></i>
    </a>


    
<!-- all script js -->
<?php include 'js.php'; ?>

<script src="../vendor/chart.js/Chart.min.js"></script>

<?php include 'testpie.php'; ?>

<?php include 'testcharts.php'; ?>

<!-- <?php include 'testbar.php'; ?> -->
<!-- <?php include 'testbar2.php'; ?> -->


<!-- Include Chart.js library -->
<!-- <script src="https://cdn.jsdelivr.net/npm/chart.js"></script> -->

<!-- <?php //include '../penjualan_obat/chartBar.php'; ?> -->




<script src="../js/dataTablesCode.js"></script>
<script src="../js/tooltipCode.js"></script>






<!-- <script>
  window.addEventListener('load', function() {
  var loader = document.getElementById('loader');
  loader.style.display = 'none'; // Hide the loader when the page has finished loading
});

</script> -->

<!-- update status kasir -->
<script>
// function updateStatus() {
//   var button = document.getElementById('statusButton');
//   var status = button.innerText === 'Aktif' ? 'Tidak aktif' : 'Aktif';
//   // var id_kasir = b;

//   // Send an AJAX request to the PHP script to update the status in the database
//   var xhr = new XMLHttpRequest();
//   xhr.open('POST', '../kasir/updateStatus.php', true);
//   xhr.setRequestHeader('Content-type', 'application/x-www-form-urlencoded');
//   xhr.onreadystatechange = function () {
//     if (xhr.readyState === 4 && xhr.status === 200) {
//       // If the status is successfully updated in the database, update the button text and color
//       if (button.innerText === 'Aktif') {
//         button.innerText = 'Tidak aktif';
//         button.classList.remove('btn-primary');
//         button.classList.add('btn-danger');
//       } else {
//         button.innerText = 'Aktif';
//         button.classList.remove('btn-danger');
//         button.classList.add('btn-primary');
//       }
//     }
//   };
//   // xhr.send('status=' + status);
//   xhr.send('status=' + status + '&id_kasir=' + id_kasir);
// }
</script>



<script>



</script>

<!-- penerimaan modal-->
<script>

// $(document).ready(function() {
//   // Open the modal when the button is clicked
//   $('#openModalButton').click(function() {
//     $('#myModalPenerimaan').show();
//   });

  // Retrieve data from the selected row and populate the form
  // $('#myTable tr').click(function() {
  //   var rowData = $(this).children('td').map(function() {
  //     return $(this).text();
  //   }).get();

  //   // Populate the input fields with the retrieved data
  //   $('#input1').val(rowData[0]);
  //   $('#input2').val(rowData[1]);
    // Set values for other input fields accordingly

    // Close the modal after retrieving the data
  //   $('#myModalPenerimaan').hide();
  // });
// });


 $(document).ready(function() {
  // Handle button click event
  $('#openModalButton').click(function() {
    var id = $(this).data('id');
    // console.log(id);
    $('#myModalPenerimaan').modal('show'); // Show the modal
  
    
    // Pass the ID to the modal
    $('#myModal').find('#idInput').val(id);
  });

  // Handle form submission
  $('#inputForm').submit(function(e) {
    e.preventDefault(); // Prevent the default form submission

    // Get the input value and the ID
    var inputValue = $(this).find('#inputValue').val();
    var id = $(this).find('#idInput').val();

    // Make AJAX request to update.php
    $.ajax({
      url: '../history/update.php', // Replace with the URL of your server-side script
      method: 'POST',
      data: { id: id, value: inputValue },
      success: function(response) {
        // Handle the response from the server
        console.log(response);
        // Refresh the table or perform any other necessary actions
      },
      error: function(xhr, status, error) {
        // Handle the error
        console.log(error);
      }
    });

    // Close the modal
    $('#myModalPenerimaan').modal('hide');
    location.reload();
  });
});


</script>

<script>
$(document).ready(function() {
  // Get the current URL and extract the page parameter value
  var urlParams = new URLSearchParams(window.location.search);
  var currentPage = urlParams.get('page');

  // Check if the current page exists in the sidebar
  if (currentPage) {
    // Add the "active" class to the appropriate elements
    $('.nav-item a[href="?page=' + currentPage + '"]').addClass('active');
    $('.nav-item a[href="?page=' + currentPage + '"]').parents('.nav-item').addClass('active');

    // Expand the parent collapse element
    $('.nav-item a[href="?page=' + currentPage + '"]').parents('.collapse').addClass('show');

    // Scroll to the active item
    var activeItem = $('.nav-item a[href="?page=' + currentPage + '"]');
    if (activeItem.length > 0) {
      var sidebar = $('#accordionSidebar');
      var scrollTop = activeItem.offset().top - sidebar.offset().top + sidebar.scrollTop() - (sidebar.height() / 2);
      sidebar.animate({ scrollTop: scrollTop }, 'slow');
    }
  }
});

</script>

<script>
  function resetDataTablesFilter(dataTableInstance) {
  dataTableInstance.search('').draw();
}

function toggleDiv(div1Id, div2Id, div3Id,div4Id, divBtnId, clearInput1,clearInput2) {
  var div1 = document.getElementById(div1Id);
  var div2 = document.getElementById(div2Id);
  var div3 = document.getElementById(div3Id);
  var div4 = document.getElementById(div4Id);
  var divBtn = document.getElementById(divBtnId);
  var clear1 = document.getElementById(clearInput1);
  var clear2 = document.getElementById(clearInput2);

  // var tableIdVar = document.getElementById(tableId);


//   var table = $('#viewSO').DataTable({
//   // DataTables configuration options
// });


  // var originalStartDate = clear1.value; // Store the original start date
  // var originalEndDate = clear2.value;   // Store the original end date




  if (div1.style.display === "none") {
    div1.style.display = "block";
    div2.style.display = "block";
    div3.style.display = "block";
    div4.style.display = "block";
    divBtn.style.backgroundColor = "gray";
    divBtn.style.borderColor = "skyblue";

  // Apply filtering based on new dates
  // applyFilter(originalStartDate, originalEndDate);

  } else {
    div1.style.display = "none";
    div2.style.display = "none";
    div3.style.display = "none";
    div4.style.display = "none";
    divBtn.style.backgroundColor = "skyblue";
    clear1.value = "0000-00-00";
    clear2.value = "0000-00-00";
    // table.draw();
  
    
  //     // Manually trigger DataTables search to reset the filtering
  // resetDataTablesFilter(table); // Pass the DataTables instance as an argument



      // Manually trigger DataTables search to reset the filtering
  // table.search('').draw(); // Assuming 'table' is your DataTables instance

 // Restore original filtering settings
//  applyFilter(originalStartDate, originalEndDate);




  }
}
// function applyFilter(startDate, endDate) {
//   // Apply your DataTables filtering logic here using startDate and endDate
// }

</script>


<!-- Modal javascript -->
<script>

 $(document).ready(function() {
  // Handle button click event
  $('.input-data-btn').click(function() {
    var id = $(this).data('id');

    $('#myModal').find('#idInput').val(id);
    // console.log(id);
    // $('#myModal').modal('show'); // Show the modal
    $.ajax({
        type: 'POST',
        url: '../cek_kesehatan/set_id.php', // Replace with the actual URL of your PHP script to set the session variable
        data: { id: id },
        success: function(response) {
          // Show the modal after setting the session variable
          $('#myModal').modal('show');
        },
        error: function(xhr, status, error) {
          // Handle AJAX error if needed
          console.error(error);
        }
      });
  
  });

  

  // Handle form submission
  $('#inputForm').submit(function(e) {
    e.preventDefault(); // Prevent the default form submission

    // Get the input value and the ID
    var inputValue = $(this).find('#inputValue').val();
    var inputValue2 = $(this).find('#inputValue2').val();
    var inputValue3 = $(this).find('#inputValue3').val();

    var id = $(this).find('#idInput').val();

    // Make AJAX request to update.php
    $.ajax({
      url: '../cek_kesehatan/update.php', // Replace with the URL of your server-side script
      method: 'POST',
      // data: { id: id, value: inputValue, value2: inputValue2 ,value3: inputValue3  },
      data: {
  id: id,
  value: inputValue !== '' ? inputValue : 0,
  value2: inputValue2 !== '' ? inputValue2 : 0,
  value3: inputValue3 !== '' ? inputValue3 : 0
},

      success: function(response) {
        // Handle the response from the server
        console.log(response);
        // Refresh the table or perform any other necessary actions
      },
      error: function(xhr, status, error) {
        // Handle the error
        console.log(error);
      }
    });

    // Close the modal
    $('#myModal').modal('hide');
    location.reload();
  });
});


</script>


<!-- code untuk checkbox-->
<!-- penampil checkbox-->
<script>
  //cek gula darah
$(document).ready(function() {
  $('#checklist').change(function() {
    if ($(this).is(':checked')) {
      var div = document.getElementById('catatan');
    div.style.display = 'block';
      $.ajax({
        url: '../cek_kesehatan/get_biaya.php',  // Replace with the actual URL of your PHP script
        method: 'GET',  // or 'POST' depending on your server-side code
        data: { id_kategori: 1 },  // Pass any required parameters to the PHP script
        success: function(response) {
          var data = JSON.parse(response);
          var price = data.biaya_kategori;
          var id = data.id_kategori;
          
          $('#targetField').val(price.toLocaleString('id-ID'));
          $('#targetFieldID').val(id);
        },
        error: function(xhr, status, error) {
          console.log('AJAX Error:', error);
        }
      });
    } else {
      var div = document.getElementById('catatan');
    div.style.display = 'none';
      $('#targetField').val('');
      $('#targetFieldID').val('');
    }
  });
});
//cek asam urat
$(document).ready(function() {
  $('#checklist2').change(function() {
    if ($(this).is(':checked')) {
      $.ajax({
        url: '../cek_kesehatan/get_biaya.php',  // Replace with the actual URL of your PHP script
        method: 'GET',  // or 'POST' depending on your server-side code
        data: { id_kategori: 2 },  // Pass any required parameters to the PHP script
        success: function(response) {
          var data = JSON.parse(response);
          var price = data.biaya_kategori;
          var id = data.id_kategori;
          
          $('#targetField2').val(price.toLocaleString('id-ID'));
          $('#targetFieldID2').val(id);
        },
        error: function(xhr, status, error) {
          console.log('AJAX Error:', error);
        }
      });
    } else {
      $('#targetField2').val('');
      $('#targetFieldID2').val('');
    }
  });
});
//cek kolesterol
$(document).ready(function() {
  $('#checklist3').change(function() {
    if ($(this).is(':checked')) {
      $.ajax({
        url: '../cek_kesehatan/get_biaya.php',  // Replace with the actual URL of your PHP script
        method: 'GET',  // or 'POST' depending on your server-side code
        data: { id_kategori: 3 },  // Pass any required parameters to the PHP script
        success: function(response) {
          var data = JSON.parse(response);
          var price = data.biaya_kategori;
          var id = data.id_kategori;
          // var formattedPrice = price.toLocaleString('id-ID', { minimumFractionDigits: 0 });
          // $('#targetField3').val(formattedPrice);

          $('#targetField3').val(price.toLocaleString('id-ID'));
          $('#targetFieldID3').val(id);
        },
        error: function(xhr, status, error) {
          console.log('AJAX Error:', error);
        }
      });
    } else {
      $('#targetField3').val('');
      $('#targetFieldID3').val('');
    }
  });
});

</script>


<script>

//update
// perhitungan checkbox
$(document).ready(function() {
  // Initialize the sum variable
  var sum = 0;

  // Function to update the sum
  function updateSum() {
    // var total = sum.toLocaleString('id-ID');
    var total = sum;

    $('#sumField').val(total);
    $('#sumFieldDisplay').val(number_format(total),0,',','.');

  }

  // Event handler for checkbox 1
  $('#checklist').change(function() {
    if ($(this).is(':checked')) {
      sum += 10000;
    } else {
      sum -= 10000;
    }

    // Update the sum field
    updateSum();
  });

  // Event handler for checkbox 2
  $('#checklist2').change(function() {
    if ($(this).is(':checked')) {
      sum += 10000;
    } else {
      sum -= 10000;
    }

    // Update the sum field
    updateSum();
  });

  // Event handler for checkbox 3
  $('#checklist3').change(function() {
    if ($(this).is(':checked')) {
      sum += 20000;
    } else {
      sum -= 20000;
    }

    // Update the sum field
    updateSum();
  });
});


</script>


<!-- ajax obat -->
 <?php  include '../stok_obat/ajaxStok.php'; ?>
 <?php  include '../stok_obat/ajaxStokEdit.php'; ?>
 <?php  include '../alkes/stok_alkes/ajaxStok.php'; ?>
 <?php  include '../alkes/stok_alkes/ajaxStokEditALK.php'; ?>



<!-- 
<?php include '../alkes/stok_alkes/stok_alkes_dropdown.php'; ?>

<?php include '../alkes/penjualan_alkes/penjualan_alkes_dropdown.php'; ?> 
<?php include '../alkes/pengadaan_alkes/pengadaan_alkes_dropdown.php'; ?>
<?php include '../alkes/penerimaan_alkes/penerimaan_alkes_dropdown.php'; ?>

-->
<!-- hitungan jual -->




<?php include '../penjualan_obat/ajaxPNJ.php'?>
<?php include '../alkes/penjualan_alkes/ajaxPNJALK.php'?>





<script>
//===================== not used ===============

$(document).ready(function() {
  // Handle change event of the first select
  $('#first_select').change(function() {
    var selectedValue = $(this).val();

    // Make an AJAX request to fetch the options for the second select
    $.ajax({
      url: '../penerimaan_obat/fetch_option.php', // Replace with the actual URL that retrieves options from the database
      method: 'POST',
      data: { selectedValue: selectedValue },
      dataType: 'json',
      success: function(response) {
        // Clear previous options in the second select
        $('#second_select').empty();

        // Add the new options to the second select
        $.each(response.data, function(index, item) {
          var option = $('<option>', {
            value: item.value,
            text: item.text
          });
          $('#second_select').append(option);
        });
      },
      error: function(xhr, status, error) {
        console.log(error); // Handle the error if any
      }
    });
  });
});


</script>

<!-- penerimaan-------------------------------------- -->

<?php include '../penerimaan_obat/PNM_obat_dropdown.php'; ?>

<?php include '../alkes/penerimaan_alkes/PNM_alkes_dropdown.php'; ?>

<!-- pengadaan-------------------------------------- -->
<script>

$(document).ready(function() {


// Counter for row IDs
let rowCount = 1;

// Add row button click event
$('#addRowBtnPGD').click(function() {
  rowCount++;

  // Clone the last row
  const newRow = $('#myTablePGD tbody tr:last').clone();

  // Update the row ID and clear input values
  newRow.attr('id', 'row' + rowCount);
  newRow.find('td:first').text(rowCount);
  newRow.find('select').val('');
  newRow.find('input').val('');

  // Append the new row to the table body
  $('#myTablePGD tbody').append(newRow);

});

// Delete row button click event
$(document).on('click', '.delete-rowPGD', function() {
  $(this).closest('tr').remove();
  updateRowNumbers();
});


// // On change event of the select_option dropdown
// $(document).on('change', '.select-options', function() {
//   var selectedOption = $(this).val();
//   var currentRow = $(this).closest('tr');

//   // Make AJAX request to fetch data based on selected option
//   // $.ajax({
//   //   url: '../penerimaan_obat/fetch_penerimaan.php',
//   //   type: 'POST',
//   //   data: { id_detail_pengadaan_obat: selectedOption },
//   //   dataType: 'json',
//   //   success: function(response) {
//   //     if (response.status === 'success') {
//   //       // Update the fields with retrieved data
//   //       currentRow.find('#result_id_obat').val(response.data.id_obat);
//   //       currentRow.find('.jumlah').val(response.data.jumlah);
//   //       currentRow.find('.satuan').val(response.data.satuan);
//         // currentRow.find('.jumlah_stok_sisa').val(response.data.jumlah_stok_obat);

//    $('#myTablePGD').on('input', '.jumlah','.satuan', function() 
//   {

//     var dd = currentRow.find('#result_id_obat').val();

//       var dd = currentRow.find('.satuan').val();
//       var jj =  currentRow.find('.jumlah').val();

//       var jumlah_stok_obat = dd - jj;

//       if (isNaN(jj)) {

//         jumlah_stok_obat = 0;

//       }

//       currentRow.find('.jumlah_stok_sisa').val(jumlah_stok_obat);
      
//     });
   


//       } else {
//         // Clear the fields if no data found
//         // currentRow.find('.jumlah_stok_obat').val('');
//         // currentRow.find('.harga').val('');
//         // currentRow.find('.jumlah_stok_sisa').val('');
//         // currentRow.find('#result_id_obat').val('');
//         currentRow.find('.jumlah').val('');
//         currentRow.find('.satuan').val('');


     

//       }
//     },
//     error: function(xhr, status, error) {
//       console.log(error); // Handle the error if any
//     }
//   });
// });

// Function to update the row numbers
function updateRowNumbers() {
  $('#myTablePGD tbody tr').each(function(index) {
    $(this).find('td:first').text(index + 1);
  });
}
});


</script>



<!-- <?php include '../alkes/pengadaan_alkes/pengadaan_alkes_dropdown.php'; ?> -->
<!-- <script>


// Attach event listener to the parent element using event delegation
$('#myTable tbody').on('input', '.qty-inputs, .unit-price-inputs', function() {
  var rows = $(this).closest('tbody').find('tr');

  rows.each(function() {
    var qty = parseFloat($(this).find('.qty-inputs').val());
    var unitPrice = parseFloat($(this).find('.unit-price-inputs').val());
    var totalAmount = qty * unitPrice;

    if (isNaN(totalAmount)) {
      totalAmount = 0;
    }

    // var formattedTotalAmounts = totalAmount.toLocaleString("id-ID");
    // $(this).find('.total-amount-inputs').val(formattedTotalAmounts);
    $(this).find('.total-amount-inputss').val(totalAmount.toLocaleString("id-ID"));
    // $(this).find('.total-amount-input2').val(totalAmount.toFixed(2));

  });
 
});

</script> -->

<script>
  //content mid view
  document.addEventListener("DOMContentLoaded", function() {
    var targetSection = document.getElementById("myTable");
    targetSection.scrollIntoView({ behavior: "smooth", block: "center" });
  });
</script>


<script>
  $(document).ready(function() {
  // ...
// var gt = 0;
  // Function to calculate and update the grand total
  function updateGrandTotals() {
var grandTotal = 0;
    
//  var grandTotal = gt.toLocaleString('id-ID');

    // Iterate over each row
    $('#myTablePNM tbody tr').each(function() {
      var totalAmount = parseFloat($(this).find('.total-amount-inputss').val());
      
      if (!isNaN(totalAmount)) {
        grandTotal += totalAmount;
      }
    });

   

    // Update the grand total field
    // $('#grandTotals').val(grandTotal.toFixed(0));
    $('#grandTotals').val(grandTotal);
  }

  // Event listener for quantity and unit price inputs
  // $('.qty-input, .unit-price-input').on('input', function() {
    $('#myTablePNM').on('input', '.qty-inputs, .unit-price-inputs', function() {
    var qty = parseFloat($(this).closest('tr').find('.qty-inputs').val());
    var unitPrice = parseFloat($(this).closest('tr').find('.unit-price-inputs').val());
    var totalAmount = qty * unitPrice;

    
    if (isNaN(totalAmount)) {
      totalAmount = 0;
    }

    $(this).closest('tr').find('.total-amount-inputss').val(totalAmount);
    // $('.jj').val(totalAmount.toFixed(0));

    updateGrandTotals(); // Calculate and update the grand total
  });

  // ...
});
</script>


<!-- <script>
  function loadCanvas() {
    // Simulate an AJAX request to fetch the canvas element (replace with your actual AJAX call)
    setTimeout(function () {
        // Create a canvas element with a specific id
        var newCanvas = document.createElement("canvas");
        newCanvas.id = "myBarCharts2"; // Set the id to "myChart"

        // Append the canvas element to the chartContainer
        var chartContainer = document.getElementById("barChartsId");
        chartContainer.innerHTML = ""; // Clear any existing content
        chartContainer.appendChild(newCanvas);

        // Now that the canvas is in the DOM, you can use your charting library to render a chart
        renderChart();
    }, 1000); // Simulate a delay, replace this with your actual AJAX call
}
</script> -->

<!-- ajax script laporan_penjualan -->

<!-- <?php include '../laporan_penjualan/labaSelectScript.php' ?> -->
<!-- <?php include '../laporan_penjualan/grafikSelectScript.php' ?> -->
<script>
        // Add event listener for form submission
        document.getElementById('filterForm').addEventListener('submit', function (e) {
            e.preventDefault(); // Prevent form submission
            updateTable();
        });

        // Function to update the table based on user selection
        function updateTable() {
            var month = document.getElementById('month').value;
            var year = document.getElementById('year').value;
            // Send AJAX request to fetch data based on month and year
            $.ajax({
                url: '../laporan_penjualan/labaFetchSelect.php',
                type: 'POST',
                data: { month: month, year: year },
                success: function (response) {
                    // Update the table with the fetched data
                    // document.getElementById('tableContainer').style.width = '100%';
                    // var jj= 9;
        var printContainer = '<a href="../laporan_penjualan/print.php?month='+month+'&year='+year+'" class="btn btn-sm btn-warning" target="_blank"><i class="fas fa-print"></i>Cetak</a>'
// <?php $selectYear ?> = year;

                    document.getElementById('printContainer').innerHTML = printContainer;
                    document.getElementById('tableContainer').innerHTML = response;
                    document.getElementById('tableContainer').style.width = '100%';
               



                }
            });
        }
    </script>


<!-- <script>
$(document).ready(function() {
  $('#medSelect').change(function() {
    var medId = $(this).val(); // Get the selected med_id

    // Make an AJAX request to fetch data from the detail_med_table
    $.ajax({
      url: '../penerimaan_obat/fetch_detail_data.php', // Replace with the actual URL that retrieves data from the detail_med_table
      method: 'POST',
      data: { medId: medId },
      dataType: 'json',
      success: function(response) {
        // Clear previous data in the table body
        $('#detailTable tbody').empty();

        // Loop through the retrieved data and append rows to the table
        $.each(response.data, function(index, item) {
          var newRow = '<tr>' +
            '<td>' + item.id_detail_pengadaan_obat + '</td>' +
            '<td>' + item.jumlah + '</td>' +
            '<td><input type="number" class="quantityInput" id="quantity_' + index + '"></td>' +
            '</tr>';

          $('#detailTable tbody').append(newRow);
        });


           // Iterate through the retrieved data and create table rows
        // for (var i = 0; i < response.data.length; i++) {
        //   var detailMedID = response.data[i].id_detail_pengadaan_obat;
        //   var stocks = response.data[i].jumlah;
        //      // Create a new table row
        //      var newRow = $('<tr>');
        //   newRow.append('<td>' + detailMedID + '</td>');
        //   newRow.append('<td>' + stocks + '</td>');

          // $('#detailTable tbody').append(newRow);
        // }
      },
      error: function(xhr, status, error) {
        console.log(error);
      }
    });
  });


  // Submit button click event
//   $('#submitBtn').click(function() {
//     var quantities = [];
//     $('.quantityInput').each(function() {
//       var quantity = $(this).val();
//       quantities.push(quantity);
//     });

//     // Perform further processing or send the quantities data to the server
//     console.log(quantities);
//   });
// });
// =======================

  $('#myForm').submit(function(e) {
    e.preventDefault(); // Prevent form submission

    // Prepare the data to be submitted
    var formData = $(this).serialize();

    // Make an AJAX request to insert the data into the database
    $.ajax({
      url: 'insert_data.php', // Replace with the actual URL that inserts data into the database
      method: 'POST',
      data: formData,
      success: function(response) {
        // Handle the success response
        console.log(response);
      },
      error: function(xhr, status, error) {
        // Handle the error response
        console.log(error);
      }
    });
  });
}); -->


<!-- </script> -->




<!-- select2 penjualan -->
<script>
//  $('#myTable').on('change', '.select-option', function() {
//   var selectedValue = $(this).val();

//   // Enable all options in all select fields
//   $('.select-option option').prop('disabled', false);

//   // Disable the selected option in all other select fields
//   $('.select-option').not(this).each(function() {
//     $(this).find('option[value="' + selectedValue + '"]').prop('disabled', true);
//   });

  // Reinitialize Select2 on all select fields to apply the changes
  // $('.select-option').select2();
// });

// update
// $(document).ready(function() {
//   // Counter for row IDs
//   let rowCount = 1;

//   // Add row button click event
//   $('#addRowBtn').click(function() {
//     rowCount++;

//     // Clone the last row
//     const newRow = $('#myTable tbody tr:last').clone();

//     // Update the row ID and clear input values
//     newRow.attr('id', 'row' + rowCount);
//     newRow.find('td:first').text(rowCount);
//     newRow.find('select').val('');
//     newRow.find('input').val('');

//     // Append the new row to the table body
//     $('#myTable tbody').append(newRow);

//     // Reinitialize Select2 on the new row's select fields
//     newRow.find('.select-option').select2();
//   });

//   // Delete row button click event
//   $(document).on('click', '.delete-row', function() {
//     $(this).closest('tr').remove();
//     updateRowNumbers();
//   });

//   // Event delegation for dynamically added rows
//   $('#myTable').on('change', '.select-option', function() {
//     var selectedValue = $(this).val();

//     // Enable all options in all select fields
//     $('.select-option option').prop('disabled', false);

//     // Disable the selected option in all other select fields
//     $('.select-option').not(this).each(function() {
//       $(this).find('option[value="' + selectedValue + '"]').prop('disabled', true);
//     });

//     // Reinitialize Select2 on all select fields to apply the changes
//     $('.select-option').select2();
//   });
// });

</script>

<!-- dropdown -->
<script>
  $(document).ready(function() {
    $('#obatDropdown').change(function() {
      var selectedId = $(this).val();
      console.log('Selected ID: ' + selectedId);
    });
  });
</script>






<script>
//fungsi datatable dibawah row like salary
// $(document).ready(function() {

// var table = $('#viewKetersediaanObat').DataTable({
//     "columnDefs": [{
//       "targets": [6],
//       "orderable": false
//     }]
//   });

// {
//         // Specify your DataTables options here
//         dom: 'Bfrtip',        
//         buttons: [
//             'colvis' // Button to show/hide columns
//         ]
//     });



// table.rows().every( function () {
//   this.child( 'Row details for row: '+this.index() );

//     // this.child( 'Row details for row: '+this.index() );

// } );
 
// $('#viewKetersediaanObat tbody').on( 'click', 'tr', function () {
//     var child = table.row( this ).child;
 
//     if ( child.isShown() ) {
//         child.hide();
//     }
//     else {
//         child.show();
//     }
// } );
// });



</script>
<!-- select2 -->
<script>
  // obat master data
$(document).ready(function() {
  $('#jenis_obat,#kategori_obat').select2({
  theme: 'bootstrap4',
  placeholder: "- Pilih -"
})
});
</script>


<script>
// $(document).ready(function() {
//   $('[data-bs-toggle="tooltip"]').tooltip();
// });


//penjualan_obat
// $(document).ready(function() {
//   $('.select-option').select2();
// });


// pengadaan_obat
// $("#id_obat").select2({
//   theme: 'bootstrap4',
//   placeholder: "- Pilih -"
// });
// $("#month,#year").select2({
//   theme: 'bootstrap4',
//   // placeholder: "- Pilih -"
//   width: 'resolve'
// });

// select2 ori
$("#jenisKelamin,#jurusan,#status").select2({
  theme: 'bootstrap4',
  placeholder: "- Pilih -"
});
</script>


</body>

</html>